using System;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;

namespace LucideBlazor.Generator;

[Generator]
public class IconGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith(".svg"))
            .Collect();

        context.RegisterSourceOutput(provider, GenerateCode);
    }

    private void GenerateCode(SourceProductionContext context, ImmutableArray<AdditionalText> files)
    {
        foreach (var file in files)
        {
            var fileName = Path.GetFileNameWithoutExtension(file.Path);
            var name = string.Concat(KebabToPascalCase(fileName), "Icon");
            var svgContent = file.GetText(context.CancellationToken)?.ToString();
            if (string.IsNullOrEmpty(svgContent)) continue;

            var doc = XDocument.Parse(svgContent);
            var svgElement = doc.Root;
            
            var innerContent = string.Concat(svgElement!.Nodes());
            var escapedContent = innerContent.Replace("\"", "\\\"");

            var source = $@"// <auto-generated/>
using Microsoft.AspNetCore.Components.Rendering;

namespace LucideBlazor
{{
    public sealed class {name} : IconBase
    {{
    private const string SvgContent = ""{escapedContent}"";

    protected override void HandleRender(RenderTreeBuilder builder)
    {{
        RenderIcon(builder, SvgContent);
    }}
    }}
}}
";
            // Add the source code to the compilation.
            context.AddSource($"{name}.g.cs", source);
        }
    }

    private static string KebabToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;

        var parts = input.Split(['-'], StringSplitOptions.RemoveEmptyEntries);

        var words = parts.Select(word => word.Length > 0
            ? char.ToUpper(word[0]) + word.Substring(1).ToLower()
            : string.Empty
        );

        return string.Concat(words);
    }
}