using System;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;

namespace LucideBlazor.Generator;

[Generator]
public class IconGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith(".svg"))
            .Collect();

        context.RegisterSourceOutput(provider, GenerateCode);
    }

    private static void GenerateCode(SourceProductionContext context, ImmutableArray<AdditionalText> files)
    {
        var mappingBuilder = new StringBuilder();
        mappingBuilder.AppendLine("// <auto-generated/>");
        mappingBuilder.AppendLine("using System;");
        mappingBuilder.AppendLine("namespace LucideBlazor");
        mappingBuilder.AppendLine("{");
        mappingBuilder.AppendLine("    internal static class IconMap");
        mappingBuilder.AppendLine("    {");
        mappingBuilder.AppendLine("        public static Type? GetIconType(string name) => name switch");
        mappingBuilder.AppendLine("        {");

        foreach (var file in files)
        {
            var fileName = Path.GetFileNameWithoutExtension(file.Path);
            var pascalName = KebabToPascalCase(fileName);
            var name = string.Concat(pascalName, "Icon");
            
            var svgContent = file.GetText(context.CancellationToken)?.ToString();
            if (string.IsNullOrEmpty(svgContent)) continue;

            var doc = XDocument.Parse(svgContent);
            var svgElement = doc.Root;

            var innerContent = string.Concat(svgElement!.Nodes());
            var escapedContent = innerContent.Replace("\"", "\\\"");

            var source = $$"""
                           // <auto-generated/>
                           using Microsoft.AspNetCore.Components.Rendering;

                           namespace LucideBlazor
                           {
                               public sealed class {{name}} : IconBase
                               {
                                   private const string SvgContent = "{{escapedContent}}";

                                   protected override void HandleRender(RenderTreeBuilder builder)
                                   {
                                       RenderIcon(builder, SvgContent);
                                   }
                               }
                           }

                           """;

            // Add the source code to the compilation.
            context.AddSource($"{name}.g.cs", source);

            // Add to mapping
            mappingBuilder.AppendLine($"            \"{fileName}\" => typeof({name}),");
        }

        mappingBuilder.AppendLine("            _ => null");
        mappingBuilder.AppendLine("        };");
        mappingBuilder.AppendLine("    }");
        mappingBuilder.AppendLine("}");

        context.AddSource("IconMap.g.cs", mappingBuilder.ToString());
    }

    private static string KebabToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;

        var parts = input.Split(['-'], StringSplitOptions.RemoveEmptyEntries);

        var words = parts.Select(word => word.Length > 0
            ? char.ToUpper(word[0]) + word.Substring(1).ToLower()
            : string.Empty
        );

        return string.Concat(words);
    }
}